---
title: "ABF"
author: "taehwan.lee"
date: "2024-01-01"
output: word_document
---

```{r}
.libPaths()
```

```{r}
library(zoo)
library(tidyverse)
library(quantmod)
library(fBasics)
library(rugarch)
library(xts)
library(PerformanceAnalytics)
```

```{r}
aapl <- read.zoo("aapl.csv", sep = ",", h=T, format = "%Y-%m-%d")
head(aapl)
```

```{r}
plot(aapl, main ="Apple Closing price on NASDAQ", ylab = "Price(USD)", xlab = "DAte")
```

```{r}
length(aapl)
```

```{r}
which.max(aapl)
```

```{r}
aapl[which.max(aapl)]
```
```{r}
aapl[3200]
```
```{r}
#단순 수익률(Simple return)
SimpleR <- diff(aapl)/stats::lag(aapl, k=-1)*100
summary(coredata(SimpleR))
```

```{r}
#지속적인 복리 수익률
ContR <- diff(log(aapl)) * 100
```
```{r}
hist(SimpleR, breaks = 100, freq = FALSE, main = "Histogram of Simple Returns", xlab = "Percent(%)")
```

```{r}
aapl_2013_1Q <- window(SimpleR, start = "2013-01-01", end = "2013-03-31")
summary(coredata(aapl_2013_1Q))
```

```{r}
hist(aapl_2013_1Q, breaks = 10, freq =FALSE, main ="Histogram of Simple Returns", xlab ="Percent(%)")
```
```{r}
#1day 95%, 99% VaR using naive historiccal approach
quantile(SimpleR, probs = c(0.05, 0.01))
```

```{r}
getSymbols("^GSPC", from = "2014-01-01", to=Sys.Date())
```

```{r}
chartSeries(Cl(GSPC))
```

```{r}
Ret <- dailyReturn(Ad(GSPC), type ="log")
Ret
```

```{r}
par(mfrow=c(2,1))
plot(Ret, main="Return")
plot(abs(Ret), main ="Absolute Value of Return")
```

```{r}
par(mfrow=c(2,2))
acf(Ret, main ="ACF of Return")
pacf(Ret, main = "PACF of Return")
acf(abs(Ret), main = "ACF of Absolute(Return)")
pacf(abs(Ret), main = "PACF of Absolute(Return)")
par(mfrow = c(1,1))
```

```{r}
R_mean <- mean(Ret); R_sd <- sd(Ret)
par(mfrow = c(1,2))
hist(Ret, nclass = 40, freq = FALSE, main ="Histogram of Return")
plot(density(Ret), main = "Distribution of Return")
x <- seq(-0.3, 0.2, 0.01)
curve(dnorm(x, mean=R_mean, sd =R_sd), from = -0.3, to = 0.2, add = TRUE, col = "red", lwd = 2)
```
```{r}
kurtosis(Ret)
```

```{r}
plot(density(Ret), xlim = c(-0.2, -0.1), ylim = c(0, 0.2), main ="Lower Tail Distribution of Return")

curve(dnorm(x, mean = R_mean, sd = R_sd), from = -0.2, to =-0.1, add = TRUE, col ="red", lwd = 2)
```
```{r}
getSymbols("AAPL", from ="2006-01-01", to ="2014-03-31")
APL_x <- dailyReturn(Cl(AAPL), type = "log")
chartSeries(APL_x)
```
```{r}
g11_spec <- ugarchspec(variance.model = list(model = "sGARCH", garchOrder = c(1,1), mean.model =list(armaOrder=c(0,0))))
g11_fit <- ugarchfit(spec = g11_spec, data = APL_x)
coef(g11_fit)
```
```{r}
g11_fit2<-ugarchfit(spec=g11_spec, data =APL_x, out.sample = 20)
g11_fore <- ugarchforecast(g11_fit2, n.ahead =10, n.roll = 5)
plot(g11_fore, which="all")
```

```{r}
fitted(g11_fore)
```
```{r}
sigma(g11_fore)
```
```{r}
uncmean(g11_fit)
```

```{r}
sqrt(uncvariance(g11_fit))
```

```{r}
uncmean(g11_fit)
```

```{r}
infocriteria(g11_fit)
```

```{r}
g11_impact <- newsimpact(g11_fit)
plot(g11_impact$zx, g11_impact$zy, type ="l", col="red", lwd = 2, main = "News Impact Analysis",
     xlab =g11_impact$xexpr, ylab = g11_impact$yexpr)
```

```{r}
eg11_spec<-ugarchspec(variance.model = list(model ="eGARCH", garchOrder = c(1,1)), mean.model = list(armaOrder=c(0,0)))
eg11_fit <-ugarchfit(spec=eg11_spec, data = APL_x)
coef(eg11_fit)
```

```{r}
eg11_impact <- newsimpact(eg11_fit)
plot(eg11_impact$zx, eg11_impact$zy, type ="l", col = "red", lwd = 2, main ="News Impact Analysis", xlab = g11_impact$xexpr, ylab = g11_impact$yexpr)
```
```{r}
infocriteria(g11_fit); infocriteria(eg11_fit)
```

```{r}
tg11_spec<-ugarchspec(variance.model = list(model = "fGARCH", submodel = "TGARCH", garchOrder = c(1,1)), mean.model = list(armaOrder = c(0,0)))
tg11_fit <- ugarchfit(spec=tg11_spec, data = APL_x)
coef(tg11_fit)
```
```{r}
tg11_impact<-newsimpact(tg11_fit)
plot(tg11_impact$zx, tg11_impact$zy, type = "l", col="red", lwd = 2, main ="News Impact Analysis", xlab = g11_impact$xexpr, ylab = g11_impact$yexpr)
```
```{r}
infocriteria(g11_fit); infocriteria(eg11_fit); infocriteria(tg11_fit)
```

```{r}
plot(density(Ret), log ='y', main ="Log Distribution of Return")
curve(dnorm(x, mean=R_mean, sd=R_sd), from = -0.3, to=0.2, log ="y", add = TRUE, col = "red", lwd = 2)
qqnorm(Ret);qqline(Ret, col ="red",lwd =2)
```

```{r}
y = rt(200, df = 5)
qqnorm(y)
qqline(y, col = 2, lwd = 2)
```

```{r}
xt <- matrix(1:6, ncol = 2, nrow = 3)
xt
```

```{r}
idxt <- as.Date("2020-01-01") + 1:3
xtsData <- xts(xt, order.by = idxt)
class(xtsData)
```
```{r}
head(xtsData)
```

```{r}
coredata(xtsData)
```
```{r}
index(xtsData)
```

```{r}
ts1 <- ts(1:10, frequency = 4, start = c(1959,2))
xts1 <- as.xts(ts1)
head(xts1)
```
```{r}
ts2<-ts(1:10, frequency = 7, start = c(12,2))
print(ts2, calendar = TRUE)
```

```{r}
xts2 <- as.xts(ts2)
```
```{r}
aapl <- read.csv("aapl.csv", h= T)
aapl
```
```{r}
idxt <- as.Date(aapl[,1])
aapl_xts <- xts(aapl[,-1], order.by = idxt)
class(aapl_xts)
head(aapl_xts)
```

```{r}
data(edhec)
edhec["2009-03", c(1,3)]
```

```{r}
edhec["2009-03/2009-05", c(1,3)]
```

```{r}
edhec[index(edhec) >"2009-05-31" & index(edhec)<= "2009-08-31", c(1,3)]
```

```{r}
q_dates<-lubridate::dmy("31/5/2009", "31/8/2009")
edhec[q_dates,1:2]
```

```{r}
xts::first(edhec[, c("Funds of Funds", "Short Selling")], "3 months")
```

```{r}
xts::last(edhec[, c("Funds of Funds", "Short Selling")], "2 months")
```

```{r}
d1<-as.Date("2019-12-31") + 1:3; x=1:3
xts1<-xts(x,order.by=d1)
xts1
```

```{r}
d2<-as.Date("2019-12-31") + 2:5; x=2:5
xts2<-xts(x,order.by=d2)
xts2
```

```{r}
xts1 + xts2
```
```{r}
merge(xts1, xts2)
```

```{r}
stats::lag(xts1, k=-1)
```
```{r}
stats::lag(xts1, k=1)
```

```{r}
na.omit(merge(xts1, xts2))
```

```{r}
merge(xts1, xts2, join="inner")
```
```{r}
merge(xts1, xts2, join="left")
```

```{r}
merge(xts1, index(xts2), fill=-1)
```

```{r}
rbind(xts1, xts2)
```

```{r}
air_xts <- as.xts(AirPassengers) %>% head(., n=24)
air_xts
```
```{r}
air_diff<-diff(air_xts, lag = 12, differences=1)
air_diff
```
```{r}
ep <- endpoints(edhec, on ="years")
ep
```
```{r}
period.apply(edhec[,"Funds of Funds"], INDEX = ep, FUN =mean) %>% head
```

```{r}
apply.yearly(edhec[,"Funds of Funds"], mean) %>% head
```

```{r}
bimonthly <- rollapply(edhec["200701/12","Funds of Funds"], 2, mean)
bimonthly
```
```{r}
edhec_3sum <- rollapply(edhec["200701/12","Funds of Funds"], 3, sum)
edhec_3sum
```

```{r}
merge(edhec["200701/12","Funds of Funds"], bimonthly, edhec_3sum)
```

